wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.17.9
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1725928474
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.11.9
      5: 0.17.9
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
max_depth:
  desc: null
  value: 7
